#!/usr/bin/env python3
"""Fix internal links that cause 404s (legacy /projects/, /states/, /locations/ paths)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Legacy /locations/{state}/... and /locations/{city}-{st}/
LOCATION_REWRITES: dict[str, str] = {
    "/locations/texas/roof-replacement/": "/texas/cost/roof-replacement/",
    "/locations/florida/roof-replacement/": "/florida/cost/roof-replacement/",
    "/locations/california/roof-replacement/": "/california/cost/roof-replacement/",
    "/locations/arizona/roof-replacement/": "/arizona/cost/roof-replacement/",
    "/locations/north-carolina/roof-replacement/": "/north-carolina/cost/roof-replacement/",
    "/locations/georgia/roof-replacement/": "/cost/roof-replacement/",
    "/locations/colorado/roof-replacement/": "/cost/roof-replacement/",
    "/locations/ohio/roof-replacement/": "/cost/roof-replacement/",
    "/locations/texas/": "/texas/",
    "/locations/florida/": "/florida/",
    "/locations/california/": "/california/",
    "/locations/arizona/": "/arizona/",
    "/locations/north-carolina/": "/north-carolina/",
    "/locations/dallas-tx/roof-replacement/": "/texas/dallas/cost/roof-replacement/",
    "/locations/houston-tx/roof-replacement/": "/texas/houston/cost/roof-replacement/",
    "/locations/austin-tx/roof-replacement/": "/texas/austin/cost/roof-replacement/",
    "/locations/miami-fl/roof-replacement/": "/florida/miami/cost/roof-replacement/",
    "/locations/phoenix-az/roof-replacement/": "/arizona/phoenix/cost/roof-replacement/",
    "/locations/atlanta-ga/roof-replacement/": "/cost/roof-replacement/",
    "/locations/denver-co/roof-replacement/": "/cost/roof-replacement/",
    "/locations/chicago-il/roof-replacement/": "/cost/roof-replacement/",
    "/locations/dallas-tx/": "/texas/dallas/",
    "/locations/houston-tx/": "/texas/houston/",
    "/locations/austin-tx/": "/texas/austin/",
    "/locations/hvac-installation/": "/hvac-cost-calculator/",
    "/locations/texas/hvac-installation/": "/texas/hvac-cost-calculator/",
    "/locations/florida/hvac-installation/": "/florida/hvac-cost-calculator/",
    "/locations/california/hvac-installation/": "/california/hvac-cost-calculator/",
    "/locations/dallas-tx/hvac-installation/": "/texas/dallas/hvac-cost-calculator/",
    "/locations/houston-tx/hvac-installation/": "/texas/houston/hvac-cost-calculator/",
    "/locations/austin-tx/hvac-installation/": "/texas/austin/hvac-cost-calculator/",
    "/locations/phoenix-az/hvac-installation/": "/arizona/phoenix/hvac-cost-calculator/",
    "/locations/miami-fl/hvac-installation/": "/florida/miami/hvac-cost-calculator/",
    "/locations/atlanta-ga/hvac-installation/": "/hvac-cost-calculator/",
    "/locations/denver-co/hvac-installation/": "/hvac-cost-calculator/",
    "/locations/chicago-il/hvac-installation/": "/hvac-cost-calculator/",
    "/locations/georgia/hvac-installation/": "/hvac-cost-calculator/",
    "/locations/arizona/hvac-installation/": "/arizona/hvac-cost-calculator/",
    "/locations/north-carolina/hvac-installation/": "/north-carolina/hvac-cost-calculator/",
    "/locations/ohio/hvac-installation/": "/hvac-cost-calculator/",
    "/locations/pennsylvania/hvac-installation/": "/hvac-cost-calculator/",
}

# Legacy /projects/{slug}/
PROJECT_REWRITES: dict[str, str] = {
    "roof-replacement-dallas-tx": "/texas/dallas/cost/roof-replacement/",
    "roof-replacement-houston-tx": "/texas/houston/cost/roof-replacement/",
    "roof-replacement-austin-tx": "/texas/austin/cost/roof-replacement/",
    "hvac-installation-dallas-tx": "/texas/dallas/hvac-cost-calculator/",
    "hvac-installation-houston-tx": "/texas/houston/hvac-cost-calculator/",
    "hvac-installation-austin-tx": "/texas/austin/hvac-cost-calculator/",
    "hvac-phoenix-az": "/arizona/phoenix/hvac-cost-calculator/",
    "fence-installation-dallas-tx": "/texas/dallas/fence-cost-calculator/",
    "fence-installation-houston-tx": "/texas/houston/fence-cost-calculator/",
    "fence-installation-austin-tx": "/texas/austin/fence-cost-calculator/",
}

OTHER_REWRITES: dict[str, str] = {
    "/states/": "/",
    "/cost/ductwork-installation/": "/hvac-cost-calculator/",
    "/cost/industrial-modern-bathroom-remodel/": "/cost/bathroom-remodel/",
    "/galley-kitchen-remodel-cost/": "/cost/kitchen-remodel/",
}

# Scoped-prefix patterns (/{state}/{city}/legacy-path)
STATE_SLUGS = ("texas", "florida", "arizona", "north-carolina", "california")


def build_redirects() -> list[str]:
    lines = [
        "# Legacy 404 fixes — auto-generated by scripts/fix-broken-links.py",
        "/states/  /  301",
        "/cost/ductwork-installation/  /hvac-cost-calculator/  301",
        "/cost/industrial-modern-bathroom-remodel/  /cost/bathroom-remodel/  301",
        "/galley-kitchen-remodel-cost/  /cost/kitchen-remodel/  301",
    ]
    for old, new in LOCATION_REWRITES.items():
        lines.append(f"{old}  {new}  301")
    for slug, new in PROJECT_REWRITES.items():
        lines.append(f"/projects/{slug}/  {new}  301")
    for state in STATE_SLUGS:
        lines.append(f"/{state}/states/  /{state}/  301")
        lines.append(f"/{state}/cost/ductwork-installation/  /{state}/hvac-cost-calculator/  301")
        lines.append(f"/{state}/cost/industrial-modern-bathroom-remodel/  /{state}/cost/bathroom-remodel/  301")
        lines.append(f"/{state}/galley-kitchen-remodel-cost/  /{state}/cost/kitchen-remodel/  301")
        for slug, new in PROJECT_REWRITES.items():
            lines.append(f"/{state}/projects/{slug}/  {new}  301")
    # City-scoped legacy paths (mirrored from root templates)
    lines.append("/:state/:city/states/  /:state/  301")
    lines.append("/:state/:city/cost/ductwork-installation/  /:state/:city/hvac-cost-calculator/  301")
    lines.append("/:state/:city/cost/industrial-modern-bathroom-remodel/  /:state/:city/cost/bathroom-remodel/  301")
    lines.append("/:state/:city/galley-kitchen-remodel-cost/  /:state/:city/cost/kitchen-remodel/  301")
    for slug, new in PROJECT_REWRITES.items():
        lines.append(f"/:state/:city/projects/{slug}/  {new}  301")
    for old, new in LOCATION_REWRITES.items():
        lines.append(f"/:state/:city{old}  {new}  301")
    return lines


def fix_href(href: str) -> str:
    if not href.startswith("/"):
        return href

    # /{state}/{city}/states/
    m = re.match(r"/([^/]+)/([^/]+)/states/?$", href)
    if m:
        return f"/{m.group(1)}/"

    # /{state}/states/
    m = re.match(r"/([^/]+)/states/?$", href)
    if m:
        return f"/{m.group(1)}/"

    # /{state}/{city}/cost/ductwork-installation/ etc.
    m = re.match(r"/([^/]+)/([^/]+)(/cost/ductwork-installation/?)$", href)
    if m:
        return f"/{m.group(1)}/{m.group(2)}/hvac-cost-calculator/"
    m = re.match(r"/([^/]+)/([^/]+)(/cost/industrial-modern-bathroom-remodel/?)$", href)
    if m:
        return f"/{m.group(1)}/{m.group(2)}/cost/bathroom-remodel/"
    m = re.match(r"/([^/]+)/([^/]+)(/galley-kitchen-remodel-cost/?)$", href)
    if m:
        return f"/{m.group(1)}/{m.group(2)}/cost/kitchen-remodel/"

    # /{state}/{city}/projects/{slug}/
    m = re.match(r"/([^/]+)/([^/]+)/projects/([^/]+)/?", href)
    if m:
        slug = m.group(3)
        if slug in PROJECT_REWRITES:
            return PROJECT_REWRITES[slug]

    # /{state}/projects/{slug}/
    m = re.match(r"/([^/]+)/projects/([^/]+)/?", href)
    if m:
        slug = m.group(2)
        if slug in PROJECT_REWRITES:
            return PROJECT_REWRITES[slug]

    # /{state}/cost/... scoped variants
    m = re.match(r"/([^/]+)(/cost/ductwork-installation/?)$", href)
    if m:
        return f"/{m.group(1)}/hvac-cost-calculator/"
    m = re.match(r"/([^/]+)(/cost/industrial-modern-bathroom-remodel/?)$", href)
    if m:
        return f"/{m.group(1)}/cost/bathroom-remodel/"
    m = re.match(r"/([^/]+)(/galley-kitchen-remodel-cost/?)$", href)
    if m:
        return f"/{m.group(1)}/cost/kitchen-remodel/"

    # /{state}/{city}/locations/...
    m = re.match(r"/([^/]+)/([^/]+)(/locations/.+)$", href)
    if m:
        inner = fix_href(m.group(3))
        if inner != m.group(3):
            return inner

    # /{state}/locations/...
    m = re.match(r"/([^/]+)(/locations/.+)$", href)
    if m:
        inner = fix_href(m.group(2))
        if inner != m.group(2):
            return inner

    if href in OTHER_REWRITES:
        return OTHER_REWRITES[href]
    if href in LOCATION_REWRITES:
        return LOCATION_REWRITES[href]

    m = re.match(r"/projects/([^/]+)/?", href)
    if m and m.group(1) in PROJECT_REWRITES:
        return PROJECT_REWRITES[m.group(1)]

    if href.endswith("/states/") or href == "/states":
        return "/"

    return href


def fix_html(html: str) -> str:
    def repl(m: re.Match[str]) -> str:
        href = m.group(1)
        new = fix_href(href)
        return f'href="{new}"'

    html = re.sub(r'href="(/[^"]*)"', repl, html)
    return html


def main() -> None:
    changed = 0
    for path in sorted(ROOT.rglob("*.html")):
        if "node_modules" in path.parts:
            continue
        original = path.read_text(encoding="utf-8")
        updated = fix_html(original)
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            changed += 1
    print(f"Fixed links in {changed} HTML file(s).")

    redirects_path = ROOT / "_redirects"
    existing = redirects_path.read_text(encoding="utf-8") if redirects_path.is_file() else ""
    legacy_block = "\n".join(build_redirects())
    if "# Legacy 404 fixes" in existing:
        existing = existing.split("# Legacy 404 fixes")[0].rstrip()
    redirects_path.write_text(existing + "\n\n" + legacy_block + "\n", encoding="utf-8")
    print(f"Updated {redirects_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
